FROM golang:1.27-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o shortener .

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/shortener .
COPY --from=builder /app/templates ./templates
COPY --from=builder /app/styles ./styles

EXPOSE 8080

CMD ["./shortener"]